add 2 vm properties to allow storage persistence
rancher/old-vm pull request #116
Opened 2018-10-12 21:41 UTC by jdoucerain

in the VM spec
  image_pvc: name of an existing pvc to persist changes done on the first virtual drive (mounted on /image)
  volumes_pvc: name of an existing pvc to persist changes done on additional virtual drives (mounted on /volumes)

Signed-off-by: jdoucerain <jerome.doucerain@bell.ca>

2018-10-12 21:46 UTC, jdoucerain commented
here is a sample manifest for a vm having persistent storage for both the image and additional volumes

apiVersion: vm.rancher.io/v1alpha1
kind: VirtualMachine
metadata:
  annotations:
  name: testvm2
spec:
  action: start
  cpus: 2
  hosted_novnc: true
  image: rancher/vm-rancheros:0.3.0
  image_pvc: image
  image_vmtools: ""
  kvm_extra_args: ""
  memory_mb: 4096
  node_name: ""
  public_keys:
  - jerome
  use_hugepages: false
  volumes_pvc: volumes

when deleting the VM and re-creating it, forcing it to be run on another node, I can get what was written to the virtual disk before deleting the VM

2018-10-23 17:38 UTC, LLParse commented on pkg/controller/vm/util.go
> +        var vmimagevolume corev1.Volume
Please use camelCase for your variables.

2018-10-23 18:04 UTC, LLParse requested changes
Looks good. Just a few minor tweaks.

2018-10-23 18:04 UTC, LLParse commented on pkg/apis/ranchervm/v1alpha1/types.go
> +        VmImagePvc string `json:"image_pvc"`
Field names are unclear, `VmImagePvcName` and `VmVolumesPvcName` would be better.

2018-10-23 18:04 UTC, LLParse commented on pkg/apis/ranchervm/v1alpha1/types.go
> +        VmVolumesPvc string `json:"volumes_pvc"`
Is Volumes plural here on purpose? I suppose if your plan is to use QCOW files as volumes, it doesn't matter if a single PV contains multiple QCOW volumes. We'll need to introduce new fields for block volume support anyways.

2018-10-24 12:24 UTC, jdoucerain commented on pkg/apis/ranchervm/v1alpha1/types.go
> +        VmVolumesPvc string `json:"volumes_pvc"`
The plural is there to indicate there could be multiple volumes in that single PVC

2018-10-24 16:41 UTC, LLParse commented on pkg/apis/ranchervm/v1alpha1/types.go
> +        VmVolumesPvc string `json:"volumes_pvc"`
I assumed that was the case. This is sufficient for a proof-of-concept, but performance won't be great. Consider your underlying PV has some IOPS guarantee which you would be effectively splitting between 1..N QCOW disk images.

That being said, QCOW likely won't perform as well as directly using a 3rd party storage provider...so let's not worry about performance now.

2018-10-24 17:55 UTC, jdoucerain commented
variables names have changed

2018-10-24 18:02 UTC, LLParse approved these changes

2018-10-24 18:03 UTC, LLParse commented
LGTM, thanks

2018-10-24 18:03 UTC, merged